const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('assert/strict'),{pathToFileURL}=require('url');
const root=path.resolve(__dirname,'..'),out=path.resolve(process.argv[2]||'/tmp/paper-feedback-revision');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
 const page=await browser.newPage(),old=await browser.newPage();await page.goto(pathToFileURL(path.join(root,'dist/Paper-Lettering-0.8.0-preview.2/纸上文字.html')).href);await old.goto(pathToFileURL(path.join(root,'dist/Paper-Lettering-0.8.0-preview.1/纸上文字.html')).href);await Promise.all([page.waitForFunction(()=>window.paperStudio?.ready),old.waitForFunction(()=>window.paperStudio?.ready)]);const checks=[];
 const project=await old.evaluate(()=>paperStudio.getProject());for(const d of project.documents){const render=async p=>p.evaluate(async d=>{await Promise.all(d.layers.map(l=>PaperFonts.ensure(l.font)));return Lettering.render(d,await Lettering.loadImage(d.image.dataURL)).toDataURL()},d);assert.equal(await render(page),await render(old));}checks.push('preview.1 两个 HarfBuzz 工程在新版本逐像素不变');
 const result=await page.evaluate(async()=>{const L=Lettering,T=PaperTypography,Q=PaperQuality;await Promise.all(['gf-notoserifsc','gf-zcoolxiaowei','gf-mashanzheng'].map(id=>PaperFonts.ensure(id)));const source='冬日，与你。',fontCases=[];const latinLayer=L.layer({renderer:'harfbuzz-2',text:'ChatGPT',font:'gf-notoserifsc',size:40,tracking:0}),latinWidths=[T.layout(latinLayer).width,T.layout({...latinLayer,tracking:4}).width];for(const font of ['gf-zcoolxiaowei','gf-mashanzheng']){const l=L.layer({renderer:'harfbuzz-2',text:source,font,size:60,tracking:3,effect:'clean',opacity:1,multiply:false}),m=T.layout(l);fontCases.push({font,source:l.text,comma:m.items.find(i=>i.text==='，').font,period:m.items.find(i=>i.text==='。').font});}
 const mixed=T.layout(L.layer({renderer:'harfbuzz-2',text:'你好，ChatGPT',font:'gf-notoserifsc',size:100,tracking:0})),comma=mixed.items.find(i=>i.text==='，'),latin=mixed.items.find(i=>i.text==='ChatGPT');
 const d={id:'test',image:{width:800,height:1100},layers:[],repairs:[]},canvas=L.canvas(800,1100);canvas.getContext('2d').fillStyle='#f3ead6';canvas.getContext('2d').fillRect(0,0,800,1100);const img=await L.loadImage(canvas.toDataURL()),centers=[.12,.31,.50,.69,.88],anchors=centers.map((coordinate,i)=>({id:'building-'+i,axis:'x',coordinate,start:.3,end:.75,label:'楼体中轴',confidence:.95})),base={font:'gf-notoserifsc',size:.045,weight:600,thickness:0,slant:0,x:.1,y:.82,rotation:0,direction:'horizontal',align:'left',tracking:0,lineHeight:1.4,color:'#443c30',effect:'clean'},brief={id:'five',name:'逐个对应',reason:'按五个参考轴居中',poetic:'no',phrases:[],layers:[...'浅深浅深浅'].map(text=>({...base,text})),alignments:centers.map((_,i)=>({layer:i,anchorId:'building-'+i,edge:'center',offset:0}))};
 const r=await Q.search([brief],{regions:[],anchors},d,img),candidate=r.candidates[0],layers=PaperDesign.layers(candidate,d),saved=L.normalizeProject({version:4,documents:[{...d,image:{...d.image,dataURL:canvas.toDataURL()},layers,palette:[]}],selectedDocumentId:d.id});
 const l=L.layer({renderer:'harfbuzz-2',font:'gf-notoserifsc',text:'每个笔画都完整',x:80,y:150,size:65,weight:600,tracking:0,color:'#302c25',opacity:1,effect:'clean',multiply:false}),art=L.render({...d,layers:[l]},img),box=Q.glyphBounds(l)[3];art.getContext('2d').drawImage(canvas,Math.floor(box.x)-1,Math.floor(box.y)-1,Math.ceil(box.w)+2,Math.ceil(box.h)+2,Math.floor(box.x)-1,Math.floor(box.y)-1,Math.ceil(box.w)+2,Math.ceil(box.h)+2);const ink=Q.visibility(d,img,[l],art)[0];
 return {latinWidths,fontCases,mixedGap:latin.x-comma.x,alignment:candidate.checks.alignment.map(a=>({target:a.target,actual:a.actual})),layers:layers.length,roundtripLayers:saved.documents[0].layers.length,renderer:saved.documents[0].layers[0].renderer,minimumGlyph:ink.minimumGlyphVisibility,overallVisibility:ink.visibleFraction,weak:ink.weakGlyphs,detailWidth:candidate.crops[0].width,sourceTexts:layers.map(l=>l.text).join('')};});
 assert.ok(result.fontCases.every(f=>f.source==='冬日，与你。'&&f.comma==='gf-notoserifsc'));assert.equal(result.fontCases[0].period,'gf-notoserifsc');assert.equal(result.mixedGap,50);assert.ok(result.latinWidths[1]>result.latinWidths[0]+20);checks.push('手写横排点号回退，原文字码不变；逗号后不叠加中西文间距');
 assert.equal(result.layers,5);assert.equal(result.roundtripLayers,5);assert.equal(result.renderer,'harfbuzz-2');assert.equal(result.sourceTexts,'浅深浅深浅');assert.ok(result.alignment.every(a=>Math.abs(a.actual-a.target)<.01));assert.ok(result.detailWidth>500);checks.push('五个文字层逐个对齐参考轴，可编辑工程往返和全部文字细节完整');
 assert.ok(result.minimumGlyph<.1&&result.overallVisibility>.65);checks.push('整层仍清晰时，单字消失也能被检查发现');
 fs.writeFileSync(path.join(out,'checks.json'),JSON.stringify({status:'passed',checks,result},null,2));console.log(JSON.stringify({status:'passed',checks,result}));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
