/* Browser acceptance using a recorded model response; no additional cloud uploads. */
const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('assert/strict'),{pathToFileURL}=require('url');
const [html,reply,out]=process.argv.slice(2).map(p=>path.resolve(p));fs.mkdirSync(out,{recursive:true});
const response=JSON.parse(fs.readFileSync(reply)),checks=[],errors=[],requests=[];
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.LETTERING_CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());let payload,delay=0,forceRewrite=false,fail=false,job=0;
 await page.route('http://127.0.0.1:49123/**',async route=>{const req=route.request(),u=new URL(req.url());let body={};if(req.method()==='OPTIONS')return route.fulfill({status:204,headers:{'Access-Control-Allow-Origin':'null','Access-Control-Allow-Headers':'Authorization,Content-Type','Access-Control-Allow-Private-Network':'true'}});if(u.pathname==='/status')body={loggedIn:true,message:'Fixture connected'};else if(u.pathname==='/advice'){payload=req.postDataJSON();requests.push(payload);body={job:String(++job)}}else if(u.pathname.startsWith('/jobs/')){if(delay)await new Promise(r=>setTimeout(r,delay));const data=structuredClone(response);data.imageSHA256=payload.imageSHA256;if(payload.copyMode==='preserve'&&!forceRewrite)for(const design of data.designs)design.layers=payload.layers.filter(l=>l.text.trim()).map(l=>({...design.layers[0],text:l.text,lineHeight:1.8}));body=fail?{state:'failed',error:'测试暂时不可用'}:{state:'complete',result:data};}await route.fulfill({json:body,headers:{'Access-Control-Allow-Origin':'null'}});});
 const url=pathToFileURL(html).href+'#bridge=http%3A%2F%2F127.0.0.1%3A49123&token='+'x'.repeat(40);await page.goto(url);await page.waitForFunction(()=>window.paperStudio?.ready&&!document.getElementById('liveDesign').disabled);await page.locator('[data-doc=p0003]').click();await page.locator('#tab-text').click();await page.locator('#text').fill('并肩看远方');await page.locator('#tab-ai').click();
 const selected=()=>page.evaluate(()=>paperStudio.getSelected()),layers=async()=>(await selected()).layers;
 const original=await layers();assert.equal(await page.locator('[name=aiCopyMode]:checked').inputValue(),'compose');await page.locator('#aiPreference').fill('写一句冬日短诗，和爱的人并肩望远');await page.locator('#aiPlacement').selectOption('right');await page.locator('#liveDesign').click();await page.waitForFunction(()=>document.getElementById('aiProgress').textContent.startsWith('方案已准备好'));assert.deepEqual(await layers(),original);await page.waitForFunction(()=>document.querySelectorAll('.design-copy').length===2);assert.equal((await page.locator('.design-copy').first().textContent()),response.designs[0].layers.map(l=>l.text).join('\n\n'));assert.equal(requests.at(-1).copyMode,'compose');assert.equal(requests.at(-1).placement,'right');checks.push('Creative brief and position reach the request; two full copy previews do not change the canvas');
 await page.locator('#quickLayout').click();await page.waitForFunction(()=>document.getElementById('quickLayoutStatus').textContent.startsWith('初排完成'));assert.deepEqual((await layers()).map(l=>l.text),response.designs[0].layers.map(l=>l.text));assert.equal((await layers())[0].lineHeight,response.designs[0].layers[0].lineHeight);await page.locator('#undo').click();assert.deepEqual(await layers(),original);checks.push('One click replaces copy and applies line spacing; one undo restores every original layer field');
 await page.locator('#tab-ai').click();await page.locator('[name=aiCopyMode][value=preserve]').check({force:true});assert.match(await page.locator('#quickLayoutLabel').textContent(),/保留原文/);await page.locator('#quickLayout').click();await page.waitForFunction(()=>document.getElementById('quickLayoutStatus').textContent.startsWith('初排完成'));assert.deepEqual((await layers()).map(l=>l.text),original.map(l=>l.text));assert.equal((await layers())[0].lineHeight,1.8);checks.push('Preserve mode keeps exact captions but applies new line spacing');
 forceRewrite=true;const kept=await layers();await page.locator('#quickLayout').click();await page.waitForFunction(()=>document.getElementById('aiProgress').textContent.includes('改动了原文'));assert.deepEqual(await layers(),kept);forceRewrite=false;checks.push('Frontend rejects a provider that rewrites copy in preserve mode');
 await page.locator('#tab-ai').click();await page.locator('[name=aiCopyMode][value=compose]').check({force:true});delay=500;await page.locator('#quickLayout').click();await page.locator('#aiPreference').fill('我在生成时修改了意境');await page.waitForFunction(()=>document.getElementById('aiProgress').textContent.startsWith('方案已保存'));assert.deepEqual(await layers(),kept);checks.push('Changing the creative brief while waiting prevents stale automatic application');
 await page.locator('#quickLayout').click();await page.locator('#tab-text').click();await page.locator('#text').fill('保留我刚改的字');await page.waitForFunction(()=>document.getElementById('aiProgress').textContent.startsWith('方案已保存'));assert.equal((await layers())[0].text,'保留我刚改的字');checks.push('Manual edits during AI generation are retained');delay=0;
 await page.locator('#addText').click();await page.locator('#text').fill('备用文字不要丢');await page.locator('#hideLayer').click();const hidden=(await layers()).find(l=>l.hidden);await page.locator('#quickLayout').click();await page.waitForFunction(()=>document.getElementById('quickLayoutStatus').textContent.startsWith('初排完成'));assert.deepEqual((await layers()).find(l=>l.id===hidden.id),hidden);assert.ok(!requests.at(-1).layers.some(l=>l.text===hidden.text));checks.push('Hidden backup layers survive generation and are omitted from the AI request');
 await page.locator('#lockLayer').click();const n=requests.length;await page.locator('#quickLayout').click();assert.equal(requests.length,n);await page.locator('#lockLayer').click();fail=true;const beforeFail=await layers();await page.locator('#quickLayout').click();await page.waitForFunction(()=>document.getElementById('aiProgress').textContent.includes('暂时不可用'));assert.deepEqual(await layers(),beforeFail);fail=false;checks.push('Locks and request failures leave the existing artwork intact');
 await page.locator('#tab-ai').click();await page.locator('#aiPreference').fill('冬日暖阳，和爱的人并肩望远，写一句原创短诗');await page.locator('#liveDesign').click();await page.waitForFunction(()=>document.getElementById('aiProgress').textContent.startsWith('方案已准备好'));await page.locator('#inspectorScroll').evaluate(e=>e.scrollTop=0);await page.screenshot({path:path.join(out,'creative-workspace.png')});await page.locator('#inspectorScroll').evaluate(e=>e.scrollTop=650);await page.screenshot({path:path.join(out,'creative-proposals.png')});
 const savedSettings=(await selected()).aiSettings;const download=page.waitForEvent('download');await page.locator('#saveProject').click();const projectFile=path.join(out,'roundtrip.paper.json');await(await download).saveAs(projectFile);await page.waitForTimeout(800);await page.reload();await page.waitForFunction(()=>window.paperStudio?.ready);assert.deepEqual((await selected()).aiSettings,savedSettings);await page.locator('[data-doc=p0002]').click();assert.equal(await page.locator('#aiPreference').inputValue(),'');await page.locator('[data-doc=p0003]').click();assert.equal(await page.locator('#aiPreference').inputValue(),savedSettings.preference);await page.locator('#projectFile').setInputFiles(projectFile);await page.waitForFunction(()=>document.getElementById('toast').textContent.includes('工程已打开'));assert.deepEqual((await selected()).aiSettings,savedSettings);checks.push('Creative settings persist per photo through drafts, export and reimport');
 for(const width of [820,390]){await page.setViewportSize({width,height:900});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.equal(await page.locator('[role=tab]').count(),4);}checks.push('Four-tab UI fits compact and mobile widths');assert.deepEqual(errors,[]);fs.writeFileSync(path.join(out,'checks.json'),JSON.stringify({status:'passed',checks,errors},null,2));console.log(JSON.stringify({status:'passed',checks,errors}));
}finally{await browser.close();}})().catch(e=>{console.error(e);fs.writeFileSync(path.join(out,'checks.json'),JSON.stringify({status:'failed',checks,errors,failure:e.stack},null,2));process.exit(1)});
