/* Chinese layout and OpenType shaping. Source text is never rewritten for glyph presentation. */
(function(g){
'use strict';
const L=g.Lettering,fonts=new Map(),faces=new Map(),cache=new Map();let hb;
const ready=(g.PaperHBReady||Promise.resolve(null)).then(value=>{hb=value;return value;});
const close=/^[，。！？、：；）］｝》〉」』】〕〗〙〛’”％%…]/u,open=/[（［｛《〈「『【〔〖〘〚‘“]$/u;
const graphemes=s=>Array.from(new Intl.Segmenter('zh',{granularity:'grapheme'}).segment(s),x=>x.segment);
const strip=s=>s.replace(/\n/g,'');
function lines(l){const text=l.text;if(l.typesetting?.source===text&&Array.isArray(l.typesetting.lines)&&strip(l.typesetting.lines.join(''))===strip(text))return l.typesetting.lines;return text.split('\n');}
function lint(parts,{poetic=false}={}){const errors=[],warnings=[];for(let i=0;i<parts.length;i++){const a=parts[i];if(close.test(a.trim()))errors.push('行首出现闭合标点');if(open.test(a.trim()))errors.push('行尾出现起始标点');if(i&&/[A-Za-z0-9]$/.test(parts[i-1])&&/^[A-Za-z0-9]/.test(a))errors.push('西文或数字被拆开');if(i&&/\d$/.test(parts[i-1])&&/^(?:[%％℃°]|cm\b|kg\b|km\b|米|年|月|日)/.test(a))errors.push('数字与单位分离');if(i&&parts[i-1].endsWith('…')&&a.startsWith('…'))errors.push('省略号被拆开');}if(parts.length>1&&graphemes(parts.at(-1).trim()).length===1&&!poetic)warnings.push('末行只有一个字');return {errors:[...new Set(errors)],warnings};}
function breaks(text,max,phrases=[]){
 const result=[];for(const paragraph of text.split('\n')){const chars=graphemes(paragraph);let start=0;while(start<chars.length){let end=Math.min(chars.length,start+Math.max(2,max));if(end<chars.length){while(end>start+1&&(close.test(chars[end])||open.test(chars[end-1])||(/[A-Za-z0-9]/.test(chars[end-1])&&/[A-Za-z0-9]/.test(chars[end]))))end--;const prefix=chars.slice(0,end).join('');for(const phrase of phrases){let at=paragraph.indexOf(phrase);while(at>=0){if(at<prefix.length&&at+phrase.length>prefix.length){const n=graphemes(paragraph.slice(0,at)).length;if(n>start)end=Math.min(end,n);else end=Math.max(end,graphemes(paragraph.slice(0,at+phrase.length)).length);}at=paragraph.indexOf(phrase,at+1);}}while(end<chars.length&&close.test(chars[end]))end++;}
 if(end<=start)end=start+1;const piece=chars.slice(start,end).join('');if(!piece.trim()&&result.length)result[result.length-1]+=piece;else result.push(piece);start=end;}if(!paragraph)result.push('');}return result;
}
function font(id,weight){const key=id+':'+weight;if(fonts.has(key))return fonts.get(key);const r=g.PaperFonts.info(id);if(!hb||!r?.dataURL)return null;if(!faces.has(id)){const bytes=Uint8Array.from(atob(r.dataURL.split(',')[1]),c=>c.charCodeAt(0)),blob=new hb.Blob(bytes.buffer);faces.set(id,{blob,face:new hb.Face(blob)});}const {blob,face}=faces.get(id),f=new hb.Font(face);f.setScale(1000,1000);if(r.weight_range)f.setVariations([new hb.Variation('wght',Math.max(r.weight_range[0],Math.min(r.weight_range[1],weight)))]);const v={f,face,blob,id};fonts.set(key,v);if(fonts.size>40)fonts.delete(fonts.keys().next().value);return v;}
function choose(id,weight,char){const preferred=font(id,weight);if(preferred?.f.nominalGlyph(char.codePointAt(0)))return preferred;return font('gf-notoserifsc',weight);}
function shapeRun(text,f,vertical,size,tracking){const buffer=new hb.Buffer();buffer.addText(text);buffer.guessSegmentProperties();buffer.setDirection(vertical?hb.Direction.TTB:hb.Direction.LTR);buffer.setLanguage('zh-cn');hb.shape(f.f,buffer);const info=buffer.getGlyphInfos(),pos=buffer.getGlyphPositions();let x=0,y=0;const s=size/1000,items=[];info.forEach((v,i)=>{items.push({font:f.id,gid:v.codepoint,path:f.f.glyphToPath(v.codepoint),ext:f.f.glyphExtents(v.codepoint),x:x+pos[i].xOffset*s,y:y-pos[i].yOffset*s,scale:s,rotation:0});x+=pos[i].xAdvance*s;y-=pos[i].yAdvance*s;if(i<info.length-1&&v.cluster!==info[i+1].cluster){if(vertical)y+=tracking;else x+=tracking;}});return {items,advance:vertical?y:x};}
function layout(l){
 if(!hb)throw new Error('排字引擎尚未就绪');const parts=lines(l),key=JSON.stringify([l.text,parts,l.font,l.weight,l.size,l.tracking,l.lineHeight,l.direction,l.align,l.slant]);if(cache.has(key))return cache.get(key);
 const vertical=l.direction==='vertical',items=[],missing=[],fallbacks=new Set(),lengths=[];let maxAlong=0;
 parts.forEach((part,index)=>{let pen=0;const tokens=part.match(/[A-Za-z0-9][A-Za-z0-9 .:/%+\-]*|[^A-Za-z0-9]+/gu)||[];for(let ti=0;ti<tokens.length;ti++){const token=tokens[ti];if(!vertical&&ti&&!/\s$/.test(tokens[ti-1])&&!/^\s/.test(token))pen+=l.size*.25;const latin=vertical&&/^[A-Za-z0-9]/.test(token),tcy=latin&&/^\d{2,3}$/.test(token);const groups=[];for(const ch of graphemes(token)){const f=choose(l.font,l.weight,ch);if(!f?.f.nominalGlyph(ch.codePointAt(0))&&!/\s/.test(ch))missing.push(ch);if(f?.id!==l.font)fallbacks.add(f?.id);const prev=groups.at(-1);if(prev?.f===f)prev.text+=ch;else groups.push({f,text:ch});}
 let tokenPen=0,tokenItems=[];for(const group of groups){if(!group.f)throw new Error('请先载入内置字体');const run=shapeRun(group.text,group.f,vertical&&!latin,l.size,l.tracking);for(const item of run.items){if(vertical&&!latin)item.y+=tokenPen;else item.x+=tokenPen;tokenItems.push(item);}tokenPen+=run.advance;}
 if(latin){const scale=tcy?Math.min(1,l.size/Math.max(1,tokenPen)):1;for(const item of tokenItems){if(tcy){item.x=item.x*scale-tokenPen*scale/2;item.y=item.y*scale+l.size*.85+pen;item.scale*=scale;}else{const x=item.x,y=item.y;item.x=-y-l.size*.35;item.y=x+pen;item.rotation=90;}}pen+=tcy?l.size+l.tracking:tokenPen+l.tracking;}else{for(const item of tokenItems){if(vertical)item.y+=pen;else item.x+=pen;}pen+=tokenPen;}
 for(const item of tokenItems){if(vertical)item.x+=(parts.length-1-index)*l.size*l.lineHeight;else item.y+=index*l.size*l.lineHeight;item.line=index;items.push(item);}
 }lengths.push(pen);maxAlong=Math.max(maxAlong,pen);});
 if(!vertical)for(const item of items)item.x+=l.align==='center'?(maxAlong-lengths[item.line])/2:l.align==='right'?maxAlong-lengths[item.line]:0;
 const corners=[];for(const item of items){const e=item.ext;if(!e)continue;const x=e.xBearing*item.scale,y=-e.yBearing*item.scale,w=e.width*item.scale,h=-e.height*item.scale,a=item.rotation*Math.PI/180;for(const [px,py] of [[x,y],[x+w,y],[x+w,y+h],[x,y+h]])corners.push({x:item.x+px*Math.cos(a)-py*Math.sin(a),y:item.y+px*Math.sin(a)+py*Math.cos(a)});}
 const minX=Math.min(0,...corners.map(p=>p.x)),minY=Math.min(0,...corners.map(p=>p.y)),maxX=Math.max(1,...corners.map(p=>p.x)),maxY=Math.max(1,...corners.map(p=>p.y));for(const item of items){item.x-=minX;item.y-=minY;}
 const rawWidth=maxX-minX,height=maxY-minY,shear=Math.tan((l.slant||0)*Math.PI/180),result={items,lines:parts.map(graphemes),widths:lengths,rawWidth,width:rawWidth+Math.abs(shear)*height,height,vertical,shear,missing:[...new Set(missing)],fallbacks:[...fallbacks].filter(Boolean)};cache.set(key,result);if(cache.size>150)cache.delete(cache.keys().next().value);return result;
}
function draw(ctx,l,m){for(const item of m.items){if(!item.path)continue;ctx.save();ctx.translate(item.x,item.y);ctx.rotate(item.rotation*Math.PI/180);ctx.scale(item.scale,-item.scale);const p=new Path2D(item.path);ctx.lineJoin='round';if(l.outlineWidth){ctx.strokeStyle=l.outlineColor;ctx.lineWidth=(l.outlineWidth*2+(l.thickness||0)*l.size)/item.scale;ctx.stroke(p);}if(l.thickness){ctx.strokeStyle=l.color;ctx.lineWidth=l.thickness*l.size/item.scale;ctx.stroke(p);}ctx.fillStyle=l.color;ctx.fill(p);ctx.restore();}}
g.PaperTypography={ready,lines,lint,breaks,layout,draw,version:'hb-1.6.1-zhCN-1'};
})(window);
