/* Live, resumable evaluation. Only approved example derivatives or synthetic fixtures leave the machine. */
const fs=require('fs'),path=require('path'),{spawn}=require('child_process'),{pathToFileURL}=require('url'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),args=process.argv.slice(2),get=(name,fallback)=>args.includes(name)?args[args.indexOf(name)+1]:fallback;
const out=path.resolve(get('--out','/tmp/paper-quality-evaluation')),ids=(get('--cases','dev-01-couple-quiet,dev-02-pet-action')).split(','),baseline=args.includes('--baseline'),live=args.includes('--live'),baselineOnly=args.includes('--baseline-only');
if(!live)throw new Error('Use --live to explicitly run account-backed image requests.');fs.mkdirSync(out,{recursive:true});
const projectFile=get('--project',null),inputProject=projectFile?JSON.parse(fs.readFileSync(projectFile)):null;
const html=path.join(root,'dist/Paper-Lettering-0.8.0-preview.1/纸上文字.html'),manifest=JSON.parse(fs.readFileSync(path.join(root,'evaluations/cases.json'))),cases=inputProject?inputProject.documents.filter(d=>!get('--document',null)||d.id===get('--document')).map(d=>({id:d.id,image:d.id,document:d,fonts:inputProject.fonts||[],preference:get('--brief',d.aiSettings?.preference||''),placement:d.aiSettings?.placement||'auto',copyMode:args.includes('--preserve')?'preserve':d.aiSettings?.copyMode||'compose',seed:0})):manifest.cases.filter(c=>ids.includes(c.id)||ids.includes(c.split));
if(!cases.length)throw new Error('No matching cases or documents');
const pause=ms=>new Promise(r=>setTimeout(r,ms));
const profileArgs=[];if(!inputProject){const profile=path.join(out,'evaluation-preferences.json');fs.writeFileSync(profile,JSON.stringify({version:1,enabled:false,entries:[]}));profileArgs.push('--preferences-file',profile);}
(async()=>{const bridge=spawn(process.env.PYTHON||'python3',['-u',path.join(root,'tools/lettering/ai/bridge.py'),'--html',html,...profileArgs],{stdio:['ignore','pipe','pipe']});let err='';bridge.stderr.on('data',v=>err+=v);const url=await new Promise((res,rej)=>{let text='';bridge.stdout.on('data',b=>{text+=b;if(text.includes('\n'))res(text.split('\n')[0]);});bridge.on('exit',()=>rej(new Error(err)));});const params=new URLSearchParams(new URL(url).hash.slice(1)),api=async(p,data)=>{const r=await fetch(params.get('bridge')+p,{method:data?'POST':'GET',headers:{Authorization:'Bearer '+params.get('token'),...(data?{'Content-Type':'application/json'}:{})},...(data?{body:JSON.stringify(data)}:{})});const v=await r.json();if(!r.ok)throw new Error(v.error);return v;};
const browser=await chromium.launch({headless:true,executablePath:process.env.LETTERING_CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'}),page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('pageerror',e=>console.error('browser:',e.message));
try{await page.goto(pathToFileURL(html).href);await page.waitForFunction(()=>paperStudio?.ready);await page.addScriptTag({path:path.join(root,'evaluations/fixtures.js')});for(const c of cases){const safeId=/^[A-Za-z0-9_-]{1,160}$/.test(c.id)?c.id:'document-'+require('crypto').createHash('sha256').update(String(c.id)).digest('hex').slice(0,20);const dir=path.join(out,safeId);fs.mkdirSync(dir,{recursive:true});if(baselineOnly?fs.existsSync(path.join(dir,'baseline.json')):fs.existsSync(path.join(dir,'creative.json'))&&(!baseline||fs.existsSync(path.join(dir,'baseline.json')))){console.log(c.id,'already complete');continue;}
 console.log(c.id,'start');const data=await page.evaluate(async c=>PaperEvaluationFixture(c),c);
 fs.writeFileSync(path.join(dir,'request.json'),JSON.stringify(data.payload,null,2));fs.writeFileSync(path.join(dir,'source.paper.json'),JSON.stringify({version:4,documents:[data.source]}));
 for(const which of baselineOnly?['baseline']:baseline?['baseline','creative']:['creative']){if(fs.existsSync(path.join(dir,which+'.json')))continue;const payload=structuredClone(data.payload);if(which==='baseline'){delete payload.version;delete payload.action;delete payload.revision;}
 let job;try{job=(await api(which==='baseline'?'/advice':'/v1/creative',payload)).job;let last='',result,steps=[];const deadline=Date.now()+735000;
 while(Date.now()<deadline){const s=await api('/jobs/'+job);if(s.phase&&s.phase!==last){console.log(c.id,which,s.phase);last=s.phase;fs.writeFileSync(path.join(dir,which+'-state.json'),JSON.stringify(s,null,2));}
 if(s.state==='awaiting_render'){const rendered=await page.evaluate(async s=>PaperQuality.search(s.briefs,s.scene,window.evaluationDoc,window.evaluationImage,{placement:window.evaluationDoc.aiSettings.placement}),s);steps.push({round:s.round,scene:s.scene,diagnostics:rendered.diagnostics});fs.writeFileSync(path.join(dir,which+'-render-round-'+s.round+'.json'),JSON.stringify({origin:'actual browser render submitted to bridge',round:s.round,revision:data.payload.revision,...rendered},null,2));fs.writeFileSync(path.join(dir,which+'-render-checks.json'),JSON.stringify(steps,null,2));await api('/jobs/'+job+'/renders',{ticket:s.ticket,revision:data.payload.revision,candidates:rendered.candidates});}
 if(s.state==='failed'||s.state==='cancelled'){fs.writeFileSync(path.join(dir,which+'-failure.json'),JSON.stringify(s,null,2));throw new Error(s.error||s.state);}if(s.state==='complete'){result=s.result;break;}await pause(1200);}
 if(!result)throw new Error('Evaluation timeout');fs.writeFileSync(path.join(dir,which+'.json'),JSON.stringify(result,null,2));const image=await page.evaluate(async r=>{await Promise.all(r.designs[0].layers.map(l=>PaperFonts.ensure(l.font)));const layers=PaperDesign.layers(r.designs[0],evaluationDoc);return Lettering.render({...evaluationDoc,layers},evaluationImage).toDataURL('image/png');},result);fs.writeFileSync(path.join(dir,which+'.png'),Buffer.from(image.split(',')[1],'base64'));const project=await page.evaluate(async r=>{const d=Lettering.copy(evaluationDoc);d.layers=[...d.layers.filter(l=>l.hidden),...PaperDesign.layers(r.designs[0],d),...d.layers.filter(l=>l.locked&&!l.hidden)];d.designSuggestions=r.designs;d.designDecision={name:r.designs[0].name,reason:r.designs[0].reason,provenance:r.provenance||null};const p=Lettering.normalizeProject({version:4,id:d.id+'-creative',documents:[d],selectedDocumentId:d.id});p.fonts=PaperFonts.used(p);return p;},result);fs.writeFileSync(path.join(dir,which+'.paper.json'),JSON.stringify(project));console.log(c.id,which,'complete',result.designs.length);
 }catch(e){if(job&&which==='creative')try{await api('/jobs/'+job+'/cancel',{});}catch(_){}console.error(c.id,which,'FAILED',e.message);fs.writeFileSync(path.join(dir,which+'-error.txt'),e.stack);}}
 }}finally{await browser.close();bridge.kill('SIGTERM');}})().catch(e=>{console.error(e);process.exit(1)});
