/* Export saved reviewed options or explicitly labelled timeout drafts with the same browser renderer. No model calls. */
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),{pathToFileURL}=require('url'),{chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),args=process.argv.slice(2),arg=name=>args[args.indexOf(name)+1];
if(!args.includes('--source')||!args.includes('--response')||!args.includes('--out'))throw new Error('Required: --source project.paper.json --response creative.json --out directory');
const source=JSON.parse(fs.readFileSync(arg('--source'))),response=JSON.parse(fs.readFileSync(arg('--response'))),out=path.resolve(arg('--out'));fs.mkdirSync(out,{recursive:true});
if(response.provenance?.qualityStatus==='draft-review-timeout'&&!args.includes('--draft'))throw new Error('Timeout drafts require --draft and must remain labelled as unreviewed');
(async()=>{const b=await chromium.launch({headless:true,executablePath:process.env.LETTERING_CHROME||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});try{const page=await b.newPage();await page.goto(pathToFileURL(path.join(root,'dist/Paper-Lettering-0.8.0-preview.2/纸上文字.html')).href);await page.waitForFunction(()=>window.paperStudio?.ready,null,{timeout:60000});await page.addScriptTag({path:path.join(root,'evaluations/fixtures.js')});const d=source.documents[0];await page.evaluate(async({d,fonts})=>PaperEvaluationFixture({id:d.id,image:d.id,document:d,fonts,copyMode:d.aiSettings?.copyMode||'preserve',placement:d.aiSettings?.placement||'auto',preference:d.aiSettings?.preference||'',seed:0}),{d,fonts:source.fonts||[]});const options=[];
for(let i=0;i<response.designs.length;i++){const design=response.designs[i],result=await page.evaluate(async r=>PaperEvaluationResult(r),{...response,designs:[design]}),png=Buffer.from(result.image.split(',')[1],'base64'),prefix='option-'+String(i+1).padStart(2,'0');
 if(i===0&&args.includes('--verify-first'))assert.deepEqual(png,fs.readFileSync(arg('--verify-first')),'Current renderer differs from the reviewed first output');
 fs.writeFileSync(path.join(out,prefix+'.png'),png);fs.writeFileSync(path.join(out,prefix+'.paper.json'),JSON.stringify(result.project));options.push({id:design.id,label:design.name,text:design.layers.map(l=>l.text).join('\n'),reason:design.reason,direction:[...new Set(design.layers.map(l=>l.direction))].join('+'),image:prefix+'.png',project:prefix+'.paper.json',previewSHA256:design.previewSHA256,parametersSHA256:design.parametersSHA256});}
fs.writeFileSync(path.join(out,'options.json'),JSON.stringify(options,null,2));console.log(JSON.stringify({exported:options.length,out}));}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
